module.exports = [
["npm:mocha@1.21.5/mocha.js", ["./mocha.css!"]],
['tests/angular.js', ['angular']],
['tests/jquery.js', ["jquery"]],
['tests/bootstrap.js', ['bootstrap', 'bootstrap/dist/css/bootstrap.css!', './bootstrap.html!text']],
['tests/jquery.js', ['jquery']],
['tests/d3.js', ['d3']],
['tests/tests.js', ['./angular.js', './bootstrap.js', './jquery.js', './d3.js', './voxel-demo.js']],
['tests/main.js', ['mocha', './tests/tests.js']],
['github:jspm/nodelibs-util@0.2.0-alpha/util.js', ["process", "./isBuffer.js"]],
['npm:game-shell@0.1.4/shell.js', ["events", "util", "domready", "vkey", "invert-hash", "uniq", "lower-bound", "iota-array", "./lib/raf-polyfill.js", "./lib/mousewheel-polyfill.js", "./lib/hrtime-polyfill.js"]],
['npm:gl-now@0.0.4/index.js', ["game-shell", "webglew"]],
["npm:ndarray-fft@0.1.0/lib/fft-matrix.js", ["bit-twiddle"]],
['npm:ndarray-fft@0.1.0/fft.js', ["ndarray-ops", "cwise", "ndarray", "./lib/fft-matrix.js", "typedarray-pool"]],
['npm:ndarray-scratch@0.0.1/scratch.js', ["ndarray", "typedarray-pool"]],
['npm:ndarray-downsample2x@0.1.1/downsample.js', ["ndarray-fft", "ndarray-scratch", "ndarray-ops", "cwise", "process"]],
['npm:tile-mip-map@0.2.1/mipmap.js', ["ndarray", "ndarray-ops", "ndarray-downsample2x"]],
['npm:gl-texture2d@0.1.12/texture.js', ["ndarray", "ndarray-ops", "typedarray-pool", "webglew"]],
['npm:gl-tile-map@0.3.0/tilemap.js', ["ndarray", "tile-mip-map", "gl-texture2d"]],
['npm:gl-buffer@0.1.2/buffer.js', ["typedarray-pool", "ndarray-ops", "ndarray"]],
['npm:gl-vao@0.0.3/lib/vao-native.js', ["./do-bind.js"]],
['npm:gl-vao@0.0.3/lib/vao-emulated.js', ["./do-bind.js"]],
['npm:gl-vao@0.0.3/vao.js', ["webglew", "./lib/vao-native.js", "./lib/vao-emulated.js"]],
['npm:esprima@1.0.4/esprima.js', ["process"]],
['npm:cwise-parser@0.0.1/index.js', ["esprima", "uniq"]],
["npm:cwise@0.3.4/cwise.js", ["cwise-parser", "cwise-compiler"]],
['npm:ndarray-fill@0.1.0/index.js', ["cwise"]],
["npm:cwise-compiler@0.0.0/lib/compile.js", ["uniq"]],
["npm:cwise-compiler@0.0.0/lib/thunk.js", ["./compile.js"]],
['npm:cwise-compiler@0.0.0/compiler.js', ["./lib/thunk.js"]],
["npm:ndarray-ops@1.1.1/ndarray-ops.js", ["cwise-compiler"]],
["npm:ndarray@1.0.18/ndarray.js", ["iota-array", "is-buffer"]],
["npm:cwise-compiler@0.1.0/lib/compile.js", ["uniq"]],
["npm:cwise-compiler@0.1.0/lib/thunk.js", ["./compile.js"]],
["npm:cwise-compiler@0.1.0/compiler.js", ["./lib/thunk.js"]],
["npm:typedarray-pool@1.1.0/pool.js", ["bit-twiddle", "dup", "buffer/global"]],
["npm:greedy-mesher@1.0.2/greedy.js", ["typedarray-pool", "uniq", "iota-array"]],
["npm:typedarray-pool@0.1.2/pool.js", ["bit-twiddle", "dup"]],
["npm:ao-mesher@0.2.10/mesh.js", ["ndarray", "cwise-compiler", "greedy-mesher", "typedarray-pool"]],
["npm:glsl-tokenizer@0.0.9/lib/literals.js", ["process"]],
["npm:glsl-tokenizer@0.0.9/lib/operators.js", ["process"]],
["npm:glsl-tokenizer@0.0.9/lib/builtins.js", ["process"]],
["npm:glsl-tokenizer@0.0.9/index.js", ["through", "./lib/literals", "./lib/operators", "./lib/builtins", "process"]],
["npm:through@1.1.2/index.js", ["stream", "process"]],
["npm:glsl-parser@0.0.9/lib/index.js", ["through", "./expr", "./scope"]],
["npm:glsl-parser@0.0.9/index.js", ["./lib/index"]],
["npm:readable-stream@2.0.5/readable.js", ["./lib/_stream_readable.js", "./lib/_stream_writable.js", "./lib/_stream_duplex.js", "./lib/_stream_transform.js", "./lib/_stream_passthrough.js", "process"]],
["npm:readable-stream@2.0.5/writable.js", ["./lib/_stream_writable.js", "process"]],
["npm:readable-stream@2.0.5/duplex.js", ["./lib/_stream_duplex.js", "process"]],
["npm:readable-stream@2.0.5/transform.js", ["./lib/_stream_transform.js", "process"]],
["npm:string_decoder@0.10.31/index.js", ["buffer", "buffer/global"]],
["npm:readable-stream@2.0.5/lib/_stream_readable.js", ["process-nextick-args", "isarray", "buffer", "events", "core-util-is", "inherits", "util", "./_stream_duplex", "string_decoder", "process", "buffer/global"]],
["npm:process-nextick-args@1.0.6/index.js", ["process"]],
["npm:readable-stream@2.0.5/lib/_stream_writable.js", ["process-nextick-args", "buffer", "core-util-is", "inherits", "util-deprecate", "events", "./_stream_duplex", "process", "buffer/global"]],
["npm:readable-stream@2.0.5/lib/_stream_duplex.js", ["process-nextick-args", "core-util-is", "inherits", "./_stream_readable", "./_stream_writable", "process"]],
["npm:readable-stream@2.0.5/lib/_stream_transform.js", ["./_stream_duplex", "core-util-is", "inherits", "process"]],
["npm:buffer@4.5.0/index.js", ["base64-js", "ieee754", "isarray", "process"]],
["github:jspm/nodelibs-buffer@0.2.0-alpha/global.js", ["./buffer.js"]],
["npm:core-util-is@1.0.2/lib/util.js", ["buffer/global"]],
["npm:readable-stream@2.0.5/lib/_stream_passthrough.js", ["./_stream_transform", "core-util-is", "inherits", "process"]],
["npm:readable-stream@2.0.5/passthrough.js", ["./lib/_stream_passthrough.js", "process"]],
["npm:stream-browserify@2.0.1/index.js", ["events", "inherits", "readable-stream/readable.js", "readable-stream/writable.js", "readable-stream/duplex.js", "readable-stream/transform.js", "readable-stream/passthrough.js"]],
["github:jspm/nodelibs-process@0.2.0-alpha/process.js", ["@system-env"]],
["npm:through@2.3.8/index.js", ["stream", "process"]],
["npm:glsl-exports@0.0.0/index.js", ["glsl-tokenizer", "glsl-parser", "through"]],
["npm:gl-shader@0.0.6/index.js", ["glsl-exports", "uniq"]],
["npm:ao-shader@0.2.3/aoshader.js", ["fs", "gl-shader"]],
["npm:voxel-demo@0.0.1/shader.js", ["gl-now", "gl-tile-map", "gl-buffer", "gl-vao", "gl-matrix", "ndarray", "ndarray-fill", "ndarray-ops", "ao-mesher", "ao-shader"]]
];